apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
data:
  password: bXktc2VjcmV0


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: port-mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: password
      volumes:
        - name: mysql-volume
          nfs:
            server: 192.168.0.7
            path: /mysql-volume
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      name: mysql-service-port
      port: 3306
      targetPort: port-mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: choistory-apiserver.kr.ncr.ntruss.com/choistory:9176384020
          ports:
          - containerPort: 8080
            name: port-api-server
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

---

apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      name: api-server-service-port
      port: 80
      targetPort: port-api-server